### PR TITLE
Run unit tests on Travis CI

### PR DESCRIPTION
**Pull request by lzanita09**

### CODE REVIEW

**Comment by priyaashah** [comment]
Not sure I know what Travis is (I will look it up), but probably a replacement for Jenkins which posed a security threat?

**Comment by lzanita09** [comment]
Yes, exactly.

**Comment by priyaashah** [comment]
I don't see removal of any Jenkins related stuff here.

**Comment by priyaashah** [comment]
I am assuming that is expected. Sorry, I don't know where the file to integrate Jenkins was.

**Pull request merged**
